language: ruby
rvm:
  - 2.4.1
  - 2.4
  - 2.3
  - 2.2

  - ruby-head
  - jruby-19mode

before_install:
  - gem update bundler

before_script:
  - bundle exec gem list

script: bundle exec ruby spec/log_spec.rb

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
