version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: run tests
          command:
            bundle exec uspec
